create table if not exists vocabulary
(
    id        bigint generated by default as identity
    primary key,
    rating    int     not null,
    translate varchar(64) not null,
    word      varchar(64) not null
);